### ISSUE TITLE
Brilliant service! A question about the background image

### ISSUE THREAD

**Issue by edent** [Juerd/tootpick#1]
This is so useful!

When hitting enter, a background image briefly loads - but it was too quick for me to see. Is this intended behaviour?

**Comment by Juerd** [comment]
The background image is just a visual gimmick, and not important to the usage of the site. It's a way to pre-cache the image for use on the buttons later, and I originally intended to use a hidden image object for that. Loading it as a background image was originally supposed to be a temporary thing because I was lazy, but I kept it because it added a gleeful touch to the service.

It does seem, however, that people want to actually see it. You're not the first to mention this issue :). I'm not sure how to handle it exactly, and there will still be a timeout because nobody likes waiting.

**Comment by Juerd** [comment]
Note: there's a timeout of 3.5 seconds now, but in other cases you will get to enjoy the image for a full 1 second. That is, if you just entered the domain for the first time.

<s>If you click a recently used instance button, you still get redirected immediately and your connection and the server are both fast, you might not get to see the background image then. Not having to wait a second time is a feature :)</s> I guess a single second is not too bad. And I just added a nice fade effect so you can see the middle of the image too.
