### ISSUE TITLE
Better URl validation

### ISSUE THREAD

**Issue by edent** [Juerd/tootpick#2]
I tried entering a FQDN - which ends with a `.` - but the form rejected it.

URl validation is hard :-)  So I suggest using https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url

That would replace:

https://github.com/Juerd/tootpick/blob/f06036476cd664d71aa296bc1930af08a4f726ca/index.html#L440

With something like:

```html
<input type="url" required value="https://" id="instance" />
```

That will also help with one of your TODO items - providing a list of suggested instances. You can do that with https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/url#providing_default_options

**Comment by Juerd** [comment]
I will support a trailing period as not supporting it is a bug, but I'm not planning on using a type="url" field, because what people enter is only the domain name. I specifically did not want to support only URLs, but also catch input like "@whreq@hsnl.social" because I suspect that many newbies will try things like that.

**Comment by edent** [comment]
That's fair enough :+1:
